import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "ar";

interface Translations {
  [key: string]: {
    en: string;
    ar: string;
  };
}

const translations: Translations = {
  // Navbar
  "nav.features": { en: "Features", ar: "المميزات" },
  "nav.howItWorks": { en: "How It Works", ar: "كيف يعمل" },
  "nav.businessCase": { en: "Business Case", ar: "الجدوى الاقتصادية" },
  "nav.pricing": { en: "Pricing", ar: "الأسعار" },
  "nav.faq": { en: "FAQ", ar: "الأسئلة الشائعة" },

  // Hero Section
  "hero.badge": { en: "Introducing a Smarter Way to Manage Your School", ar: "نقدم طريقة أذكى لإدارة مدرستك" },
  "hero.title1": { en: "Know Where Every", ar: "اعرف أين كل" },
  "hero.title2": { en: "Student Is.", ar: "طالب." },
  "hero.title3": { en: "Every Second.", ar: "كل ثانية." },
  "hero.subtitle": { en: "Transform attendance and transportation with QR-based tracking, real-time bus GPS, and instant parent notifications.", ar: "حوّل نظام الحضور والمواصلات مع تتبع QR، GPS الحافلات في الوقت الفعلي، وإشعارات فورية للآباء." },
  "hero.cta.features": { en: "Explore Features", ar: "استكشف المميزات" },
  "hero.cta.roi": { en: "Calculate Your ROI", ar: "احسب عائد استثمارك" },
  "hero.trust.scans": { en: "Sub-second scans", ar: "مسح فوري" },
  "hero.trust.gps": { en: "Real-time GPS tracking", ar: "تتبع GPS مباشر" },
  "hero.trust.alerts": { en: "Instant parent alerts", ar: "تنبيهات فورية للآباء" },
  "hero.stat.scanTime": { en: "Scan Time", ar: "وقت المسح" },
  "hero.stat.alertDelivery": { en: "Alert Delivery", ar: "إرسال التنبيه" },
  "hero.stat.fewerCalls": { en: "Fewer Calls", ar: "مكالمات أقل" },
  "hero.dashboard.live": { en: "Live Dashboard", ar: "لوحة تحكم مباشرة" },
  "hero.dashboard.inClass": { en: "Students In Class", ar: "طلاب في الفصل" },
  "hero.dashboard.inTransit": { en: "In Transit", ar: "في الطريق" },
  "hero.dashboard.activity": { en: "Recent Activity", ar: "النشاط الأخير" },
  "hero.activity.checkedIn": { en: "Emma W. checked in", ar: "سارة دخلت" },
  "hero.activity.busArrived": { en: "Bus #2 arrived at school", ar: "الحافلة #2 وصلت المدرسة" },
  "hero.activity.notification": { en: "Parent notification sent", ar: "تم إرسال إشعار للولي" },
  "hero.activity.accounted": { en: "All students accounted for", ar: "تم حصر جميع الطلاب" },
  "hero.activity.justNow": { en: "Just now", ar: "الآن" },
  "hero.activity.minAgo": { en: "min ago", ar: "دقائق" },

  // Problem Solution Section
  "problemSolution.title": { en: "The Problem We Solve", ar: "المشكلة التي نحلها" },
  "problemSolution.subtitle": { en: "Schools struggle with outdated attendance systems. Parents worry. Staff is overwhelmed.", ar: "تعاني المدارس من أنظمة حضور قديمة. الآباء قلقون. الموظفون مرهقون." },
  "problemSolution.challenges": { en: "Current Challenges", ar: "التحديات الحالية" },
  "problemSolution.solution": { en: "SAMS Solution", ar: "حل SAMS" },
  "problem.manualAttendance.title": { en: "Manual Attendance Wastes Time", ar: "تسجيل الحضور اليدوي يضيع الوقت" },
  "problem.manualAttendance.desc": { en: "Teachers spend 15+ minutes daily on roll call instead of teaching.", ar: "يقضي المعلمون أكثر من 15 دقيقة يومياً في تسجيل الحضور بدلاً من التدريس." },
  "problem.parentsInDark.title": { en: "Parents Left in the Dark", ar: "الآباء في حيرة" },
  "problem.parentsInDark.desc": { en: "No real-time visibility into whether their child arrived safely.", ar: "لا توجد رؤية فورية حول وصول أطفالهم بأمان." },
  "problem.inaccurateRecords.title": { en: "Inaccurate Records", ar: "سجلات غير دقيقة" },
  "problem.inaccurateRecords.desc": { en: "Paper-based systems lead to errors and compliance headaches.", ar: "الأنظمة الورقية تؤدي إلى أخطاء ومشاكل في الامتثال." },
  "problem.officeOverwhelmed.title": { en: "Office Overwhelmed", ar: "المكتب مثقل" },
  "problem.officeOverwhelmed.desc": { en: "Staff fielding constant calls about student whereabouts.", ar: "الموظفون يردون على مكالمات مستمرة حول مكان الطلاب." },
  "solution.qrScans.title": { en: "Sub-Second QR Scans", ar: "مسح QR فوري" },
  "solution.qrScans.desc": { en: "Students check in instantly with a quick bracelet scan.", ar: "يسجل الطلاب حضورهم فوراً بمسح سريع للسوار." },
  "solution.parentAlerts.title": { en: "Instant Parent Alerts", ar: "تنبيهات فورية للآباء" },
  "solution.parentAlerts.desc": { en: "Real-time notifications when their child arrives or boards the bus.", ar: "إشعارات فورية عند وصول طفلهم أو صعوده للحافلة." },
  "solution.digitalAccuracy.title": { en: "Digital Accuracy", ar: "دقة رقمية" },
  "solution.digitalAccuracy.desc": { en: "100% accurate records with timestamps and audit trails.", ar: "سجلات دقيقة 100% مع طوابع زمنية ومسارات تدقيق." },
  "solution.fewerCalls.title": { en: "90% Fewer Office Calls", ar: "تقليل المكالمات 90%" },
  "solution.fewerCalls.desc": { en: "Parents have answers at their fingertips via the app.", ar: "الآباء لديهم الإجابات في متناول أيديهم عبر التطبيق." },

  // Features Section
  "features.label": { en: "FEATURES", ar: "المميزات" },
  "features.title": { en: "Everything You Need", ar: "كل ما تحتاجه" },
  "features.subtitle": { en: "A complete solution for attendance, transportation, communication, and compliance.", ar: "حل متكامل للحضور والمواصلات والتواصل والامتثال." },
  "features.qrBracelet.title": { en: "QR Bracelet System", ar: "نظام سوار QR" },
  "features.qrBracelet.desc": { en: "Durable, waterproof bracelets with unique QR codes. Works offline with automatic sync.", ar: "أساور متينة ومقاومة للماء مع رموز QR فريدة. تعمل بدون اتصال مع مزامنة تلقائية." },
  "features.busGps.title": { en: "Real-Time Bus GPS", ar: "GPS الحافلات المباشر" },
  "features.busGps.desc": { en: "Track every bus on a live map. Get ETA updates and route deviation alerts.", ar: "تتبع كل حافلة على خريطة مباشرة. احصل على تحديثات وقت الوصول وتنبيهات الانحراف عن المسار." },
  "features.notifications.title": { en: "Instant Notifications", ar: "إشعارات فورية" },
  "features.notifications.desc": { en: "Push notifications and email alerts to parents within 10 seconds of any event.", ar: "تنبيهات فورية وبريد إلكتروني للآباء خلال 10 ثوانٍ من أي حدث." },
  "features.parentApp.title": { en: "Parent Mobile App", ar: "تطبيق الآباء" },
  "features.parentApp.desc": { en: "iOS and Android app for parents to track their child and bus in real-time.", ar: "تطبيق iOS وAndroid للآباء لتتبع أطفالهم والحافلة في الوقت الفعلي." },
  "features.analytics.title": { en: "Analytics Dashboard", ar: "لوحة التحليلات" },
  "features.analytics.desc": { en: "Attendance trends, tardiness patterns, and bus efficiency metrics at a glance.", ar: "اتجاهات الحضور وأنماط التأخر ومقاييس كفاءة الحافلات في لمحة." },
  "features.emergency.title": { en: "Emergency Mode", ar: "وضع الطوارئ" },
  "features.emergency.desc": { en: "Instant student location lookup and evacuation tracking during emergencies.", ar: "بحث فوري عن موقع الطالب وتتبع الإخلاء أثناء الطوارئ." },
  "features.tardy.title": { en: "Tardy Tracking", ar: "تتبع التأخير" },
  "features.tardy.desc": { en: "Automatic late detection based on bell schedules with reason code logging.", ar: "كشف تلقائي للتأخير بناءً على جداول الجرس مع تسجيل أكواد السبب." },
  "features.wrongBus.title": { en: "Wrong Bus Alerts", ar: "تنبيهات الحافلة الخاطئة" },
  "features.wrongBus.desc": { en: "Instant notification if a student boards the wrong bus route.", ar: "إشعار فوري إذا صعد الطالب إلى حافلة خاطئة." },
  "features.ferpa.title": { en: "FERPA Compliant", ar: "متوافق مع FERPA" },
  "features.ferpa.desc": { en: "Enterprise-grade security with encryption and privacy compliance.", ar: "أمان على مستوى المؤسسات مع التشفير والامتثال للخصوصية." },
  "features.multiSchool.title": { en: "Multi-School Support", ar: "دعم متعدد المدارس" },
  "features.multiSchool.desc": { en: "District-level dashboard with cross-school reporting and centralized billing.", ar: "لوحة تحكم على مستوى المنطقة مع تقارير متعددة المدارس وفواتير مركزية." },
  "features.billing.title": { en: "Integrated Billing", ar: "فوترة متكاملة" },
  "features.billing.desc": { en: "Automated invoicing with family discounts and payment plan support.", ar: "فواتير آلية مع خصومات عائلية ودعم خطط الدفع." },
  "features.reports.title": { en: "Report Generator", ar: "مولد التقارير" },
  "features.reports.desc": { en: "Daily attendance sheets, compliance reports, and custom exports.", ar: "كشوف حضور يومية وتقارير امتثال وتصدير مخصص." },
  "features.category.attendance": { en: "Attendance", ar: "الحضور" },
  "features.category.transportation": { en: "Transportation", ar: "المواصلات" },
  "features.category.communication": { en: "Communication", ar: "التواصل" },
  "features.category.analytics": { en: "Analytics", ar: "التحليلات" },
  "features.category.safety": { en: "Safety", ar: "السلامة" },
  "features.category.security": { en: "Security", ar: "الأمان" },
  "features.category.admin": { en: "Admin", ar: "الإدارة" },

  // How It Works Section
  "howItWorks.label": { en: "HOW IT WORKS", ar: "كيف يعمل" },
  "howItWorks.title": { en: "How the QR Code Attendance System Works", ar: "كيف يعمل نظام حضور رمز QR" },
  "howItWorks.subtitle": { en: "A seamless ecosystem that tracks every student, every step of the way.", ar: "نظام متكامل يتتبع كل طالب في كل خطوة." },
  "howItWorks.ecosystem": { en: "The QR Code Ecosystem", ar: "نظام رمز QR" },
  "howItWorks.workflow": { en: "The Daily Attendance Workflow", ar: "سير العمل اليومي للحضور" },
  "howItWorks.ecosystem1.title": { en: "Every Student Gets a Unique QR Code", ar: "كل طالب يحصل على رمز QR فريد" },
  "howItWorks.ecosystem1.desc": { en: "Printed on student ID cards, this code is the primary identifier for all attendance.", ar: "مطبوع على بطاقات هوية الطلاب، هذا الرمز هو المعرف الأساسي لكل الحضور." },
  "howItWorks.ecosystem2.title": { en: "Each Bus Route Has a Dedicated QR Code", ar: "كل مسار حافلة له رمز QR مخصص" },
  "howItWorks.ecosystem2.desc": { en: "Posted inside the bus, it's used to verify students are on the correct route.", ar: "معلق داخل الحافلة، يستخدم للتحقق من أن الطلاب على المسار الصحيح." },
  "howItWorks.ecosystem3.title": { en: "Every Class Session is Assigned a QR Code", ar: "كل حصة دراسية لها رمز QR" },
  "howItWorks.ecosystem3.desc": { en: "This ensures attendance is recorded for the correct subject, period, and room.", ar: "هذا يضمن تسجيل الحضور للمادة والفترة والغرفة الصحيحة." },
  "howItWorks.step1.title": { en: "Morning Bus Boarding", ar: "صعود الحافلة الصباحي" },
  "howItWorks.step1.desc": { en: "A bus attendant uses a device to scan each student's ID card upon boarding.", ar: "يستخدم مرافق الحافلة جهازاً لمسح بطاقة كل طالب عند الصعود." },
  "howItWorks.step2.title": { en: "Classroom Check-In", ar: "تسجيل الحضور في الفصل" },
  "howItWorks.step2.desc": { en: "The teacher scans each student's ID at the door for every class period.", ar: "يمسح المعلم بطاقة كل طالب عند الباب لكل حصة." },
  "howItWorks.step3.title": { en: "Automated Record-Keeping", ar: "حفظ السجلات الآلي" },
  "howItWorks.step3.desc": { en: "All scans are instantly timestamped and logged, and absences are automatically identified.", ar: "جميع المسوحات مختومة بالوقت ومسجلة فوراً، والغيابات يتم تحديدها تلقائياً." },
  "howItWorks.step": { en: "Step", ar: "خطوة" },
  "howItWorks.inProgress": { en: "In progress...", ar: "قيد التنفيذ..." },
  "howItWorks.result.title": { en: "100% Accurate Attendance", ar: "حضور دقيق 100%" },
  "howItWorks.result.desc": { en: "All records instantly synced to the cloud", ar: "جميع السجلات تتزامن فوراً مع السحابة" },

  // Business Case Section
  "businessCase.label": { en: "Executive Business Case", ar: "دراسة الجدوى التنفيذية" },
  "businessCase.title": { en: "A Bulletproof Financial Story", ar: "قصة مالية محكمة" },
  "businessCase.subtitle": { en: "Comprehensive investment analysis designed for school boards, principals, and finance committees. Clear numbers. Zero risk. Obvious decision.", ar: "تحليل استثماري شامل مصمم لمجالس المدارس والمديرين ولجان المالية. أرقام واضحة. مخاطر صفر. قرار واضح." },
  "businessCase.smallSchool": { en: "Small School", ar: "مدرسة صغيرة" },
  "businessCase.mediumSchool": { en: "Medium School", ar: "مدرسة متوسطة" },
  "businessCase.largeSchool": { en: "Large School", ar: "مدرسة كبيرة" },
  "businessCase.configure": { en: "Configure", ar: "إعداد" },
  "businessCase.parameters": { en: "Parameters", ar: "المعايير" },
  "businessCase.students": { en: "Number of Students", ar: "عدد الطلاب" },
  "businessCase.buses": { en: "Number of Buses", ar: "عدد الحافلات" },
  "businessCase.rooms": { en: "Number of Rooms", ar: "عدد الغرف" },
  "businessCase.enrollment": { en: "100% enrollment", ar: "تسجيل 100%" },
  "businessCase.gpsTracking": { en: "GPS tracking", ar: "تتبع GPS" },
  "businessCase.classroomsOffices": { en: "Classrooms + offices", ar: "فصول + مكاتب" },
  "businessCase.dailyCost": { en: "Daily cost per student:", ar: "التكلفة اليومية لكل طالب:" },
  "businessCase.subscriptionDaily": { en: "Subscription (daily):", ar: "الاشتراك (يومياً):" },
  "businessCase.totalCostDaily": { en: "Total cost (daily):", ar: "إجمالي التكلفة (يومياً):" },
  "businessCase.notCostCenter": { en: "This Is Not a Cost Center", ar: "هذا ليس مركز تكلفة" },
  "businessCase.valueGenerating": { en: "It's a value-generating, risk-free investment", ar: "إنه استثمار مولّد للقيمة وخالٍ من المخاطر" },
  "businessCase.zeroBudget": { en: "Zero Budget Impact", ar: "صفر تأثير على الميزانية" },
  "businessCase.zeroBudgetDesc": { en: "Costs integrate seamlessly into tuition fees", ar: "التكاليف تندمج بسلاسة في رسوم التعليم" },
  "businessCase.predictableRevenue": { en: "Predictable Revenue", ar: "إيرادات متوقعة" },
  "businessCase.predictableRevenueDesc": { en: "Stable, recurring income stream for the school", ar: "تدفق دخل ثابت ومتكرر للمدرسة" },
  "businessCase.strategicData": { en: "Strategic Data Asset", ar: "أصل بيانات استراتيجي" },
  "businessCase.strategicDataDesc": { en: "Insights that improve operations & outcomes", ar: "رؤى تحسن العمليات والنتائج" },
  "businessCase.tabs.investment": { en: "Investment Breakdown", ar: "تفصيل الاستثمار" },
  "businessCase.tabs.projections": { en: "5-Year Projections", ar: "توقعات 5 سنوات" },
  "businessCase.tabs.zeroRisk": { en: "Zero-Risk Model", ar: "نموذج صفر مخاطر" },
  "businessCase.tabs.dataValue": { en: "Data & Analytics", ar: "البيانات والتحليلات" },

  // Investment Tab
  "businessCase.hardwareInvestment": { en: "Hardware Investment", ar: "استثمار الأجهزة" },
  "businessCase.item": { en: "Item", ar: "العنصر" },
  "businessCase.qty": { en: "Qty", ar: "الكمية" },
  "businessCase.unit": { en: "Unit", ar: "الوحدة" },
  "businessCase.total": { en: "Total", ar: "الإجمالي" },
  "businessCase.studentBracelets": { en: "Student Bracelets", ar: "أساور الطلاب" },
  "businessCase.classroomTablets": { en: "Classroom Tablets", ar: "أجهزة الفصول" },
  "businessCase.gpsBusModules": { en: "GPS Bus Modules", ar: "وحدات GPS الحافلات" },
  "businessCase.chargingStations": { en: "Charging Stations", ar: "محطات الشحن" },
  "businessCase.serverHardware": { en: "Server Hardware", ar: "خادم الأجهزة" },
  "businessCase.networkEquipment": { en: "Network Equipment", ar: "معدات الشبكة" },
  "businessCase.hardwareSubtotal": { en: "Hardware Subtotal", ar: "إجمالي الأجهزة" },
  "businessCase.installationSetup": { en: "Installation & Setup", ar: "التركيب والإعداد" },
  "businessCase.service": { en: "Service", ar: "الخدمة" },
  "businessCase.cost": { en: "Cost", ar: "التكلفة" },
  "businessCase.installationLabor": { en: "Installation Labor", ar: "عمالة التركيب" },
  "businessCase.softwareConfiguration": { en: "Software Configuration", ar: "تكوين البرنامج" },
  "businessCase.staffTraining": { en: "Staff Training", ar: "تدريب الموظفين" },
  "businessCase.projectManagement": { en: "Project Management", ar: "إدارة المشروع" },
  "businessCase.setupSubtotal": { en: "Setup Subtotal", ar: "إجمالي الإعداد" },
  "businessCase.totalInitialInvestment": { en: "Total Initial Investment", ar: "إجمالي الاستثمار الأولي" },
  "businessCase.annualOperatingCosts": { en: "Annual Operating Costs (Recurring)", ar: "تكاليف التشغيل السنوية (متكررة)" },
  "businessCase.platformLicense": { en: "Platform License", ar: "ترخيص المنصة" },
  "businessCase.maintenanceSupport": { en: "Maintenance & Support", ar: "الصيانة والدعم" },
  "businessCase.estReplacements": { en: "Est. Replacements", ar: "البدائل المقدرة" },
  "businessCase.cloudHosting": { en: "Cloud Hosting", ar: "الاستضافة السحابية" },
  "businessCase.totalAnnualCosts": { en: "Total Annual Operating Costs", ar: "إجمالي تكاليف التشغيل السنوية" },
  "businessCase.year": { en: "/year", ar: "/سنة" },

  // Projections Tab
  "businessCase.revenueSources": { en: "Revenue Sources (from Parent Subscriptions)", ar: "مصادر الإيرادات (من اشتراكات الآباء)" },
  "businessCase.enrolledStudents": { en: "Enrolled Students", ar: "الطلاب المسجلون" },
  "businessCase.100enrollment": { en: "100% enrollment", ar: "تسجيل 100%" },
  "businessCase.annualSubscriptions": { en: "Annual Subscriptions", ar: "الاشتراكات السنوية" },
  "businessCase.perStudentYear": { en: "$125/student/year", ar: "$125/طالب/سنة" },
  "businessCase.firstYearDeposits": { en: "First-Year Deposits", ar: "تأمينات السنة الأولى" },
  "businessCase.perStudentRefundable": { en: "$25/student (refundable)", ar: "$25/طالب (مسترد)" },
  "businessCase.replacementFees": { en: "Replacement Fees", ar: "رسوم الاستبدال" },
  "businessCase.annualLossRate": { en: "~3% annual loss rate", ar: "~3% معدل فقدان سنوي" },
  "businessCase.year1Revenue": { en: "Year 1 Total Revenue", ar: "إجمالي إيرادات السنة الأولى" },
  "businessCase.5yearProjection": { en: "5-Year Financial Projection (Standard Model)", ar: "التوقعات المالية لـ 5 سنوات (النموذج القياسي)" },
  "businessCase.yearLabel": { en: "Year", ar: "السنة" },
  "businessCase.revenue": { en: "Revenue", ar: "الإيرادات" },
  "businessCase.costs": { en: "Costs", ar: "التكاليف" },
  "businessCase.netProfit": { en: "Net Profit", ar: "صافي الربح" },
  "businessCase.cumulative": { en: "Cumulative", ar: "التراكمي" },
  "businessCase.breakEvenPoint": { en: "Break-Even Point", ar: "نقطة التعادل" },
  "businessCase.months": { en: "months", ar: "شهر" },
  "businessCase.5yearTotalProfit": { en: "5-Year Total Profit", ar: "إجمالي ربح 5 سنوات" },
  "businessCase.5yearROI": { en: "5-Year ROI", ar: "عائد استثمار 5 سنوات" },
  "businessCase.cumulativeProfitVisualization": { en: "5-Year Cumulative Profit Visualization", ar: "تصور الربح التراكمي لـ 5 سنوات" },

  // Zero-Risk Tab
  "businessCase.zeroRiskTitle": { en: "The Zero-Risk Tuition Model", ar: "نموذج الرسوم الدراسية صفر المخاطر" },
  "businessCase.zeroRiskSubtitle": { en: "Eliminate financial risk. Guarantee positive returns.", ar: "إزالة المخاطر المالية. ضمان عوائد إيجابية." },
  "businessCase.withoutTuition": { en: "Without Tuition Integration", ar: "بدون دمج الرسوم الدراسية" },
  "businessCase.withTuition": { en: "With Tuition Integration", ar: "مع دمج الرسوم الدراسية" },
  "businessCase.schoolPaysHardware": { en: "School pays for all hardware upfront", ar: "المدرسة تدفع ثمن جميع الأجهزة مقدماً" },
  "businessCase.budgetApprovalNeeded": { en: "Budget approval needed for capital expense", ar: "موافقة الميزانية مطلوبة للنفقات الرأسمالية" },
  "businessCase.adoptionRisk": { en: "Risk if parent adoption is lower", ar: "مخاطر إذا كان تبني الآباء أقل" },
  "businessCase.longerBreakEven": { en: "Longer break-even timeline", ar: "جدول زمني أطول للتعادل" },
  "businessCase.parentsPayHardware": { en: "Parents pay for hardware via tech fee", ar: "الآباء يدفعون ثمن الأجهزة عبر رسوم التقنية" },
  "businessCase.noCapitalRequired": { en: "No capital expenditure required", ar: "لا نفقات رأسمالية مطلوبة" },
  "businessCase.guaranteedEnrollment": { en: "100% enrollment = guaranteed returns", ar: "تسجيل 100% = عوائد مضمونة" },
  "businessCase.positiveROIMonth1": { en: "Positive ROI from month one", ar: "عائد إيجابي من الشهر الأول" },
  "businessCase.howItWorks": { en: "How Tuition Integration Works", ar: "كيف يعمل دمج الرسوم الدراسية" },
  "businessCase.techFeeAdded": { en: "Tech Fee Added to Tuition", ar: "رسوم التقنية تُضاف للرسوم الدراسية" },
  "businessCase.perStudentAnnual": { en: "/student/annual", ar: "/طالب/سنوياً" },
  "businessCase.coversHardwareBreakdown": { en: "Covers hardware cost + annual subscription", ar: "تغطي تكلفة الأجهزة + الاشتراك السنوي" },
  "businessCase.dailyCostPerStudent": { en: "Daily cost per student:", ar: "التكلفة اليومية لكل طالب:" },
  "businessCase.lessThanCoffee": { en: "Less than a cup of coffee", ar: "أقل من فنجان قهوة" },
  "businessCase.tuitionBreakEven": { en: "Break-Even (Tuition Model)", ar: "نقطة التعادل (نموذج الرسوم)" },
  "businessCase.instantBreakEven": { en: "Instant", ar: "فوري" },
  "businessCase.profitFromDay1": { en: "Profit from day 1", ar: "ربح من اليوم الأول" },
  "businessCase.schoolInvestment": { en: "School Investment", ar: "استثمار المدرسة" },
  "businessCase.oneTimeSetup": { en: "One-time setup only", ar: "إعداد لمرة واحدة فقط" },
  "businessCase.5yearProfit": { en: "5-Year Profit", ar: "ربح 5 سنوات" },
  "businessCase.projectionWithTuition": { en: "5-Year Projection (With Tuition Integration)", ar: "توقعات 5 سنوات (مع دمج الرسوم)" },
  "businessCase.whyBoardApprovalEasy": { en: "Why This Makes Board Approval Easy", ar: "لماذا يسهّل هذا موافقة المجلس" },
  "businessCase.noLargeCapital": { en: "No large capital expenditure required", ar: "لا نفقات رأسمالية كبيرة مطلوبة" },
  "businessCase.predictableRevenueStream": { en: "Predictable, stable revenue stream", ar: "تدفق إيرادات مستقر ومتوقع" },
  "businessCase.positiveROIFromMonth1": { en: "Positive ROI from month one", ar: "عائد إيجابي من الشهر الأول" },
  "businessCase.enhancedSafety": { en: "Enhanced safety adds parent value", ar: "السلامة المحسنة تضيف قيمة للآباء" },
  "businessCase.competitiveAdvantage": { en: "Competitive advantage vs. other schools", ar: "ميزة تنافسية مقابل المدارس الأخرى" },
  "businessCase.noUncertainROI": { en: "No uncertain ROI or adoption risk", ar: "لا عائد غير مؤكد أو مخاطر تبني" },

  // Data & Analytics Tab
  "businessCase.strategicDataAsset": { en: "Strategic Data Asset", ar: "أصل البيانات الاستراتيجي" },
  "businessCase.insightsSubtitle": { en: "The insights your school would never get otherwise", ar: "الرؤى التي لن تحصل عليها مدرستك بخلاف ذلك" },
  "businessCase.strategicDataFullDesc": { en: "Beyond attendance tracking, this system gives you access to structured data that transforms how you understand your students, operations, and outcomes. This is a major strategic advantage that compounds over time.", ar: "بخلاف تتبع الحضور، يمنحك هذا النظام وصولاً إلى بيانات منظمة تحول فهمك لطلابك وعملياتك ونتائجك. هذه ميزة استراتيجية كبرى تتراكم مع الوقت." },
  "businessCase.studentAttendanceData": { en: "Student & Attendance Data", ar: "بيانات الطلاب والحضور" },
  "businessCase.data.attendancePatterns": { en: "Individual attendance patterns & trends", ar: "أنماط واتجاهات الحضور الفردية" },
  "businessCase.data.absencePrediction": { en: "Absence prediction & early intervention", ar: "التنبؤ بالغياب والتدخل المبكر" },
  "businessCase.data.chronicAbsenteeism": { en: "Chronic absenteeism identification", ar: "تحديد الغياب المزمن" },
  "businessCase.data.arrivalDeparture": { en: "Arrival/departure time analytics", ar: "تحليلات وقت الوصول/المغادرة" },
  "businessCase.data.classEngagement": { en: "Class-by-class engagement metrics", ar: "مقاييس المشاركة لكل فصل" },
  "businessCase.data.historicalRecords": { en: "Historical attendance records", ar: "سجلات الحضور التاريخية" },
  "businessCase.operationalAnalytics": { en: "Operational Analytics", ar: "التحليلات التشغيلية" },
  "businessCase.data.busRoute": { en: "Bus route optimization data", ar: "بيانات تحسين مسارات الحافلات" },
  "businessCase.data.peakTraffic": { en: "Peak traffic time analysis", ar: "تحليل أوقات الذروة" },
  "businessCase.data.classroomUtilization": { en: "Classroom utilization metrics", ar: "مقاييس استخدام الفصول" },
  "businessCase.data.staffEfficiency": { en: "Staff efficiency insights", ar: "رؤى كفاءة الموظفين" },
  "businessCase.data.resourceAllocation": { en: "Resource allocation optimization", ar: "تحسين تخصيص الموارد" },
  "businessCase.data.emergencyResponse": { en: "Emergency response time tracking", ar: "تتبع وقت الاستجابة للطوارئ" },
  "businessCase.performanceOutcomes": { en: "Performance & Outcomes", ar: "الأداء والنتائج" },
  "businessCase.data.attendanceGrade": { en: "Attendance-to-grade correlation", ar: "ارتباط الحضور بالدرجات" },
  "businessCase.data.engagementScoring": { en: "Student engagement scoring", ar: "تقييم مشاركة الطلاب" },
  "businessCase.data.retentionRisk": { en: "Retention risk indicators", ar: "مؤشرات مخاطر الاحتفاظ" },
  "businessCase.data.academicTrends": { en: "Academic performance trends", ar: "اتجاهات الأداء الأكاديمي" },
  "businessCase.data.behaviorPatterns": { en: "Behavior pattern analysis", ar: "تحليل أنماط السلوك" },
  "businessCase.data.learningPredictions": { en: "Learning outcome predictions", ar: "توقعات نتائج التعلم" },
  "businessCase.reportingCompliance": { en: "Reporting & Compliance", ar: "التقارير والامتثال" },
  "businessCase.data.governmentReports": { en: "Automated government reports", ar: "تقارير حكومية آلية" },
  "businessCase.data.accreditation": { en: "Accreditation documentation", ar: "وثائق الاعتماد" },
  "businessCase.data.parentComms": { en: "Parent communication logs", ar: "سجلات تواصل الآباء" },
  "businessCase.data.safetyIncident": { en: "Safety incident tracking", ar: "تتبع حوادث السلامة" },
  "businessCase.data.auditReady": { en: "Audit-ready records", ar: "سجلات جاهزة للتدقيق" },
  "businessCase.data.customReports": { en: "Custom report generation", ar: "إنشاء تقارير مخصصة" },
  "businessCase.strategicAdvantages": { en: "Strategic Advantages for School Leadership", ar: "المزايا الاستراتيجية لقيادة المدرسة" },
  "businessCase.improvePerformance": { en: "Improve Performance", ar: "تحسين الأداء" },
  "businessCase.improvePerformanceDesc": { en: "Identify at-risk students early. Correlate attendance with academic outcomes. Make data-driven interventions that actually work.", ar: "تحديد الطلاب المعرضين للخطر مبكراً. ربط الحضور بالنتائج الأكاديمية. اتخاذ تدخلات مبنية على البيانات تعمل فعلاً." },
  "businessCase.boostRetention": { en: "Boost Retention", ar: "تعزيز الاحتفاظ" },
  "businessCase.boostRetentionDesc": { en: "Understand which families are disengaging before they leave. Track parent satisfaction through engagement metrics.", ar: "فهم العائلات التي تنسحب قبل مغادرتها. تتبع رضا الآباء من خلال مقاييس المشاركة." },
  "businessCase.enhanceReputation": { en: "Enhance Reputation", ar: "تعزيز السمعة" },
  "businessCase.enhanceReputationDesc": { en: "Market your school as technology-forward and safety-focused. Use data to demonstrate outcomes to prospective parents.", ar: "تسويق مدرستك كمتقدمة تقنياً ومركزة على السلامة. استخدام البيانات لإثبات النتائج للآباء المحتملين." },
  "businessCase.dataOwnership": { en: "Your Data, Your Ownership", ar: "بياناتك، ملكيتك" },
  "businessCase.dataOwnershipDesc": { en: "All data collected belongs to your school. Full export capabilities, API access for integration with existing systems, and FERPA-compliant storage. We're a tool for your success, not a data broker.", ar: "جميع البيانات المجمعة ملك لمدرستك. قدرات تصدير كاملة، وصول API للتكامل مع الأنظمة الحالية، وتخزين متوافق مع FERPA. نحن أداة لنجاحك، لسنا وسيط بيانات." },

  // Final CTA
  "businessCase.readyToPresent": { en: "Ready to Present This to Your Board?", ar: "جاهز لتقديم هذا لمجلسك؟" },
  "businessCase.downloadDesc": { en: "Download our complete executive summary package with all financials, projections, and presentation materials.", ar: "حمّل حزمة الملخص التنفيذي الكاملة مع جميع البيانات المالية والتوقعات ومواد العرض." },
  "businessCase.downloadPackage": { en: "Download Executive Package", ar: "تحميل الحزمة التنفيذية" },

  // Zero-Risk Tab Additional
  "businessCase.schoolAbsorbs": { en: "School absorbs", ar: "تتحمل المدرسة" },
  "businessCase.upfront": { en: "upfront", ar: "مقدماً" },
  "businessCase.budgetApprovalRequired": { en: "Budget approval process required", ar: "مطلوب عملية موافقة الميزانية" },
  "businessCase.monthBreakEven": { en: "-month break-even period", ar: " شهر فترة التعادل" },
  "businessCase.financialRisk": { en: "Financial risk if adoption is lower than expected", ar: "مخاطر مالية إذا كان التبني أقل من المتوقع" },
  "businessCase.schoolInvestsOnly": { en: "School invests only", ar: "تستثمر المدرسة فقط" },
  "businessCase.setupCosts": { en: "(setup costs)", ar: "(تكاليف الإعداد)" },
  "businessCase.hardwareCostPassed": { en: "Hardware cost passed to parents via tuition", ar: "تكلفة الأجهزة تُمرر للآباء عبر الرسوم الدراسية" },
  "businessCase.breakEvenInJust": { en: "Break-even in just", ar: "التعادل في" },
  "businessCase.monthsOnly": { en: "months", ar: "شهر فقط" },
  "businessCase.guaranteedPositiveCashFlow": { en: "Guaranteed positive cash flow from day one", ar: "تدفق نقدي إيجابي مضمون من اليوم الأول" },
  "businessCase.recommendedTuitionFee": { en: "Recommended Tuition Fee Structure", ar: "هيكل الرسوم الدراسية الموصى به" },
  "businessCase.recommended": { en: "Recommended", ar: "موصى به" },
  "businessCase.annualTechFee": { en: "Annual Technology Fee", ar: "رسوم التقنية السنوية" },
  "businessCase.studentYear": { en: "/student/year", ar: "/طالب/سنة" },
  "businessCase.includesHardware": { en: "Includes:", ar: "يشمل:" },
  "businessCase.hardwarePlusService": { en: "hardware +", ar: "أجهزة +" },
  "businessCase.serviceWord": { en: "service", ar: "خدمة" },
  "businessCase.oneTime": { en: "one-time", ar: "مرة واحدة" },
  "businessCase.returnedUponGraduation": { en: "Returned upon graduation or transfer", ar: "يُسترد عند التخرج أو النقل" },
  "businessCase.dailyCostLabel": { en: "Daily Cost", ar: "التكلفة اليومية" },
  "businessCase.perDay": { en: "/day", ar: "/يوم" },
  "businessCase.parentValueProposition": { en: "Parent Value Proposition", ar: "القيمة المقدمة للآباء" },
  "businessCase.parentValueDesc": { en: "When presenting to parents, frame the fee as invaluable peace of mind:", ar: "عند العرض للآباء، قدم الرسوم كراحة بال لا تقدر بثمن:" },
  "businessCase.parentValue1": { en: "Real-time arrival/departure notifications", ar: "إشعارات الوصول/المغادرة في الوقت الفعلي" },
  "businessCase.parentValue2": { en: "Live GPS tracking of school buses", ar: "تتبع GPS مباشر لحافلات المدرسة" },
  "businessCase.parentValue3": { en: "Instant attendance alerts", ar: "تنبيهات حضور فورية" },
  "businessCase.parentValue4": { en: "Emergency location services", ar: "خدمات موقع الطوارئ" },
  "businessCase.parentValue5": { en: "Direct teacher communication", ar: "تواصل مباشر مع المعلم" },
  "businessCase.parentValue6": { en: "Complete daily activity log", ar: "سجل نشاط يومي كامل" },

  // Pricing Section
  "pricing.label": { en: "PRICING", ar: "الأسعار" },
  "pricing.title": { en: "Simple, Transparent Pricing", ar: "أسعار بسيطة وشفافة" },
  "pricing.subtitle": { en: "Choose the plan that fits your school. All plans include hardware and training.", ar: "اختر الخطة المناسبة لمدرستك. جميع الخطط تشمل الأجهزة والتدريب." },
  "pricing.schoolPlans": { en: "School Subscription Plans", ar: "خطط اشتراك المدارس" },
  "pricing.parentOptions": { en: "Parent Subscription Options", ar: "خيارات اشتراك الآباء" },
  "pricing.basic": { en: "Basic", ar: "أساسي" },
  "pricing.premium": { en: "Premium", ar: "متميز" },
  "pricing.enterprise": { en: "Enterprise", ar: "مؤسسي" },
  "pricing.basicDesc": { en: "Essential attendance tracking", ar: "تتبع الحضور الأساسي" },
  "pricing.premiumDesc": { en: "Full tracking with parent app", ar: "تتبع كامل مع تطبيق الآباء" },
  "pricing.enterpriseDesc": { en: "Multi-school & district", ar: "متعدد المدارس والمناطق" },
  "pricing.year": { en: "/year", ar: "/سنة" },
  "pricing.recommended": { en: "Recommended", ar: "موصى به" },
  "pricing.bestValue": { en: "Best Value", ar: "أفضل قيمة" },
  "pricing.getStarted": { en: "Get Started", ar: "ابدأ الآن" },
  "pricing.setupAnnual": { en: "Setup + Annual", ar: "إعداد + سنوي" },
  "pricing.annualNoSetup": { en: "Annual, No Setup", ar: "سنوي، بدون إعداد" },
  "pricing.refundableDeposit": { en: "refundable deposit", ar: "تأمين مسترد" },
  "pricing.onlyPerDay": { en: "Only $0.69/day", ar: "فقط $0.69/يوم" },
  "pricing.familyDiscounts": { en: "Family Discounts:", ar: "خصومات العائلة:" },
  "pricing.secondChild": { en: "15% off 2nd child", ar: "15% خصم للطفل الثاني" },
  "pricing.thirdChild": { en: "25% off 3rd+ child", ar: "25% خصم للثالث فأكثر" },
  "pricing.feature.qrAttendance": { en: "QR attendance scanning", ar: "مسح حضور QR" },
  "pricing.feature.basicReporting": { en: "Basic reporting", ar: "تقارير أساسية" },
  "pricing.feature.upTo200": { en: "Up to 200 students", ar: "حتى 200 طالب" },
  "pricing.feature.emailSupport": { en: "Email support", ar: "دعم البريد" },
  "pricing.feature.webDashboard": { en: "Web dashboard", ar: "لوحة تحكم ويب" },
  "pricing.feature.everythingBasic": { en: "Everything in Basic", ar: "كل ما في الأساسي" },
  "pricing.feature.busGps": { en: "Real-time bus GPS tracking", ar: "تتبع GPS الحافلات" },
  "pricing.feature.parentApp": { en: "Parent mobile app", ar: "تطبيق الآباء" },
  "pricing.feature.advancedAnalytics": { en: "Advanced analytics", ar: "تحليلات متقدمة" },
  "pricing.feature.upTo500": { en: "Up to 500 students", ar: "حتى 500 طالب" },
  "pricing.feature.prioritySupport": { en: "Priority support", ar: "دعم أولوية" },
  "pricing.feature.everythingPremium": { en: "Everything in Premium", ar: "كل ما في المتميز" },
  "pricing.feature.multiSchool": { en: "Multi-school dashboard", ar: "لوحة متعددة المدارس" },
  "pricing.feature.apiAccess": { en: "API access", ar: "وصول API" },
  "pricing.feature.customIntegrations": { en: "Custom integrations", ar: "تكاملات مخصصة" },
  "pricing.feature.unlimitedStudents": { en: "Unlimited students", ar: "طلاب غير محدودين" },
  "pricing.feature.dedicatedManager": { en: "Dedicated success manager", ar: "مدير نجاح مخصص" },

  // FAQ Section
  "faq.label": { en: "FAQ", ar: "الأسئلة الشائعة" },
  "faq.title": { en: "Frequently Asked Questions", ar: "الأسئلة المتكررة" },
  "faq.subtitle": { en: "Everything you need to know about SAMS.", ar: "كل ما تحتاج معرفته عن SAMS." },
  "faq.q1": { en: "How long does implementation take?", ar: "كم يستغرق التطبيق؟" },
  "faq.a1": { en: "Most schools are fully operational within 2-3 weeks. This includes hardware installation, staff training, and parent onboarding. Our team handles everything.", ar: "معظم المدارس تعمل بالكامل خلال 2-3 أسابيع. يشمل ذلك تركيب الأجهزة وتدريب الموظفين وتسجيل الآباء. فريقنا يتولى كل شيء." },
  "faq.q2": { en: "What happens if a bracelet is lost or damaged?", ar: "ماذا يحدث إذا فُقد السوار أو تلف؟" },
  "faq.a2": { en: "Replacement bracelets cost $15 each and can be issued same-day. We keep spare inventory at each school. Lost bracelets can be immediately deactivated to prevent misuse.", ar: "تكلفة السوار البديل $15 ويمكن إصداره في نفس اليوم. نحتفظ بمخزون احتياطي في كل مدرسة. الأساور المفقودة يمكن تعطيلها فوراً لمنع سوء الاستخدام." },
  "faq.q3": { en: "Does it work without internet?", ar: "هل يعمل بدون إنترنت؟" },
  "faq.a3": { en: "Yes! Our system works offline with automatic sync. Attendance data is stored locally and uploads when connectivity returns. You'll never lose a scan.", ar: "نعم! نظامنا يعمل بدون اتصال مع مزامنة تلقائية. بيانات الحضور تُخزن محلياً وتُرفع عند عودة الاتصال. لن تفقد أي مسح." },
  "faq.q4": { en: "How secure is the student data?", ar: "ما مدى أمان بيانات الطلاب؟" },
  "faq.a4": { en: "We use bank-level encryption and are fully FERPA compliant. All data is stored in SOC 2 certified data centers. We never share or sell student information.", ar: "نستخدم تشفير بمستوى البنوك ونحن متوافقون تماماً مع FERPA. جميع البيانات مخزنة في مراكز بيانات معتمدة SOC 2. لا نشارك أو نبيع معلومات الطلاب." },
  "faq.q5": { en: "Can parents opt out?", ar: "هل يمكن للآباء الانسحاب؟" },
  "faq.a5": { en: "Yes. The parent app and notifications are optional. Non-participating students still get bracelets for attendance tracking, but parents won't receive alerts.", ar: "نعم. تطبيق الآباء والإشعارات اختيارية. الطلاب غير المشاركين يحصلون على أساور لتتبع الحضور، لكن الآباء لن يتلقوا تنبيهات." },
  "faq.q6": { en: "What about students who walk or get dropped off?", ar: "ماذا عن الطلاب الذين يمشون أو يُوصَّلون؟" },
  "faq.a6": { en: "They scan their bracelet at classroom entrance terminals just like bus riders. The system tracks all students equally regardless of how they arrive.", ar: "يمسحون سوارهم عند أجهزة مدخل الفصل مثل ركاب الحافلة. النظام يتتبع جميع الطلاب بالتساوي بغض النظر عن طريقة وصولهم." },
  "faq.q7": { en: "How accurate is the GPS tracking?", ar: "ما مدى دقة تتبع GPS؟" },
  "faq.a7": { en: "Our GPS modules update every 10 seconds with accuracy within 10 feet. Parents see real-time bus location and accurate ETAs based on traffic conditions.", ar: "وحدات GPS لدينا تُحدَّث كل 10 ثوانٍ بدقة 3 أمتار. الآباء يرون موقع الحافلة مباشرة ووقت الوصول المتوقع بناءً على حالة المرور." },
  "faq.q8": { en: "What training is provided?", ar: "ما التدريب المقدم؟" },
  "faq.a8": { en: "We provide on-site training for all staff, including teachers, office administrators, and bus drivers. We also provide video tutorials and 24/7 support.", ar: "نقدم تدريباً في الموقع لجميع الموظفين، بما في ذلك المعلمين ومديري المكاتب وسائقي الحافلات. نقدم أيضاً دروس فيديو ودعم على مدار الساعة." },

  // Footer
  "footer.brand": { en: "School Attendance Management System", ar: "نظام إدارة حضور المدرسة" },
  "footer.features": { en: "Features", ar: "المميزات" },
  "footer.howItWorks": { en: "How It Works", ar: "كيف يعمل" },
  "footer.pricing": { en: "Pricing", ar: "الأسعار" },
  "footer.roiCalculator": { en: "ROI Calculator", ar: "حاسبة العائد" },
  "footer.faq": { en: "FAQ", ar: "الأسئلة الشائعة" },
  "footer.copyright": { en: "© 2025 School Attendance Management System (SAMS)", ar: "© 2025 نظام إدارة حضور المدرسة (SAMS)" },
  "footer.madeWith": { en: "Made with", ar: "صُنع بـ" },
  "footer.forEducators": { en: "for educators", ar: "للمعلمين" },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[key]?.[language] || key;
  };

  const isRTL = language === "ar";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div dir={isRTL ? "rtl" : "ltr"} className={isRTL ? "font-arabic" : ""}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
